name: PlayerFreeze
version: 0.0.1
author: Evan Straw
main: pw.evan.PlayerFreeze.Main
description: Allows for players to be frozen in place, preventing them from moving or otherwise playing the game.
softdepend: [ActionBarAPI]
commands:
  freeze:
    description: Freezes a player. The player will not be able to move or place or break blocks.
    permission: playerfreeze.freeze
    usage: "Usage: /freeze <player> [time]"
  freezeall:
    description: Freezes all players (except those who are exempt).
    permisson: playerfreeze.freeze.all
    usage: "Usage: /freezeall [time]"
  unfreeze:
    description: Unfreezes a player.
    permission: playerfreeze.unfreeze
    usage: "Usage: /unfreeze <player>"
  unfreezeall:
    description: Unfreezes all frozen players.
    permission: playerfreeze.unfreeze.all
    usage: "Usage: /unfreezeall"
permissions:
  playerfreeze.freeze:
    description: Allows the use of the /freeze command
    default: false
  playerfreeze.freeze.all:
    description: Allows the use of the /freezeall command
    default: false
  playerfreeze.unfreeze:
    description: Allows the use of the /unfreeze command
    default: false
  playerfreeze.unfreeze.all:
    description: Allows the use of the /unfreezeall command
    default: false
  playerfreeze.exempt:
    description: Allows the player to be exempt from freezing commands targeting them
    default: false