name: PlayerFreeze
version: 1.0.2
author: Evan Straw
main: pw.evan.PlayerFreeze.Main
description: Allows for players to be frozen in place, preventing them from moving or otherwise playing the game.
softdepend: [ActionBarAPI]
commands:
  freeze:
    description: Freezes a player. The player will not be able to move or place or break blocks.
    usage: "Usage: /freeze <player> [time]"
  freezeall:
    description: Freezes all players (except those who are exempt).
    usage: "Usage: /freezeall [time]"
  unfreeze:
    description: Unfreezes a player.
    usage: "Usage: /unfreeze <player>"
  unfreezeall:
    description: Unfreezes all frozen players.
    usage: "Usage: /unfreezeall"
permissions:
  playerfreeze.freeze:
    description: Allows the use of the /freeze command
    default: false
  playerfreeze.freezeall:
    description: Allows the use of the /freezeall command
    default: false
  playerfreeze.unfreeze:
    description: Allows the use of the /unfreeze command
    default: false
  playerfreeze.unfreezeall:
    description: Allows the use of the /unfreezeall command
    default: false
  playerfreeze.exempt:
    description: Allows the player to be exempt from freezing commands targeting them
    default: false